Algoritmo "maior ou menor"
// Descrição   : lê um valor e exibe uma mensagem caso seja maior de 10;
//               exibe outra mensagem caso não seja maior que 10.
// Autor(a)    : Israel Soares
// Data atual  : 22/03/2023
Var

   numero : inteiro

Inicio

   escreval("digite um número: ")
   leia(numero)
   
   limpatela
   
   se(numero > 10) entao
       escreval("MAIOR QUE 10!")
   senao
       escreval("MENOR QUE 10!")
   fimse

Fimalgoritmo