Algoritmo "numeros impares"
// Descrição   : mostra os números impares entre 100 e 200.
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/04/2023
Var
// Seção de Declarações das variáveis 
numero : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

escreval("números impares entre 100 e 200")
escreval()

para numero de 100 ate 200 faca

     se (numero % 2 = 1)  entao
         escreval(numero)
     fimse

fimpara

Fimalgoritmo